language: node_js
dist: trusty
node_js:
- '8'
env:
  global:
  - secure: TLivqf5lb81s4YrqDtyWOa5S0FY9+wWgc8cyLAZN3H4Migfut94F6LmLbsxTk532Fsob0L/d7TfRUhVOj4t65KkSNZfMgmf4445VC4arGX68E6usTkxJ43/yF3wdej8bjBE7G4nCkTG/rR0dVb7xrJjgn1k6v9J+K7Rx9oJWZVyIuS4EPhxrUnYFqMjWm8pwoGwu1C4XxK+w3a+GoIXI5RU76MA07V29tnnIyRNyQVJ+hUhYgXosZicPRD6pNUL/okDv9U59gVtSGBUN2h7YYKi1emKXR2mLDnB6AdWPZbmCRE+C5ygNDwfnwPkHPvOVLSA0S9Nw9Amq7J5djYfbPXVTYUGlaC1RYKxeNyLBpSvqgcmIe7VkKUMtRlwiEmjfgopDzcNEQHgsV7pfyXu8oovZAwHVGnt3KZ3VV2aUS10FBCLB0O0u9ctxMxlSHx3a7eoiLufDvsPrkDm9f1cLzm3Ly7WPmmN4CM4MId6AMf7X+R88HaTVboPyVH+SlTpLgVv+AkVR4nGQw+QbDi5XpflSrs1jEWVZaPOPQpmV60cCG1PZxpMrPmRGht8pjDnx8vCQ8JU+wYe4psCpa+6gdKi7lXWF0LF+fWBhgzbq4ndM3L+2Ky2aVLuYGxxgH08eJN747ZajUG6dP1XhPhjPRFZUCjY5a/o4WqAsndRaQ+4=
  - AWS_ACCESS_KEY_ID=AKIAIEKKCTFCDTGKKHMA
  - secure: OS133zdQIrp0Qliv6P1COebwEiR9wS2I9KPrFnZLj/HbyCyCfXzzNGT806o2O3Dis1ihkYggpQGPYVnh8J6PerWXnQ6LlgzXRmw+u4XQfRpaJkhAqSl9aWrtYAglpzWgr9jUrY092hRsUSa8rrCsbCqEBKHBLlPqY9iSgQcsaf/r2ZVYWgh9vOhdR9W9jBepQSBtSBbCubJo9isfe4z2gR2rCznay1u0sf2L6ElJuAnp7UpZKvoYk4KgAh+RGCSeXvSKlaZ52PtQZaBAUoSez2VuBWje4p5vMOgi1O5uHFL+90LlvRbyHIKC4IMdnzMWHfn/TrG0/lG8Xuubtg19NaehDGQ4JULI33qRg5EExTVCfoWUQ1r5enuYn/2JDnsw1NlGMC2+IgvxStpqLUMpPCzdJWc4xoQ/YcltTZzLLfYaH07ELxtqh+3e3kiqj2Oek5w0nk7hA77Ghl/+SMNVNYfOU2lbigjuvhCpq4do6z7U3IB3quXCo5AO7PPGtR2QRDOHq0dY0GYqPFaNH7ONG6qGM4vrAcA73KCOSOeUgv15OynwgOWNlfOVfj7eaD1etBomIvde8+/qCf1rhJI9O+J00g1Ug89du8JXchzFKueEv0OChl0dC2NbcjChJID3+yLSpvvhG97Tgev0XiYiN4LQXKf3TBx2ZU8gedpt80M=
  - secure: q9kSTNJirw/wLnl4P4G1iFKSnI01zQMXIYsJhfFU4sr4DsmI7mnK6FSNbNKDNdkaLvqw2HXgkGCtqtxLSibeGh3CadK0qRxJF2j7DuKYNie1zyBw9oAH4R3xwrFSywXZv2JI/abiYuT460PkYYC5hm+U4kGrgbYoHc7nrMeRFaXJh0Yf0a00EgDkWQTWcgHNRvgqMPezrtiu8yX7R4fh1aJbRDJdzZw1Ukt00+K2YzkaWMc9/NzF4A3lLwmP0AqeH5IQdOuqNKo0jBYQLju8IPLD1kHHKsLGjb+8Hacml3q3xY8wuRh0UAjh8YiZ3w9ABED7B3dqhtWsXxSMdBFE4cT4auDKnKEbS9SZmEJSajrgJ0dXHsF2drDoDLAJ9kcjbIeEHxvatxzb/gFRN0gaZWcQczDVvskkynTwRisZbjVXHZv4bvIl23BcNzzoy6I2tX9x/7EFkK0yP/bi2GAl/C/NhVPm1a91byixDgundPv3emnnWknlbDjwAaCv1sJSM4rMs3w8aVkT7N8q/pQp56VJBWBMlYvqPoXOwfKQoAwv9Wh8BzeZHMs3O84mO1ghXIT1ljbEkcq4Mz+FgH3Kwdoi6ekybFfq9DMaK6N62uPfeeIpchDqOnI9RKUBKIIgiFh/Jm800TzljNiMj7VXOJw5DWy61qALSWeSG9UKVS8=
  - SENTRY_ORG=randytarampi
  - SENTRY_PROJECT=words
before_install:
- uname -a
- lscpu
- npm install -g npm
- npm install -g serverless
- if [ -z "$TRAVIS_TAG" ]; then export NODE_ENV=prd; else export NODE_ENV=dev; fi;
script: NODE_ENV=test npm test
after_success:
- mkdir -p ../dpl_cd_upload
- tar -zcf ../dpl_cd_upload/me.photos.tar.gz -C ./ .
- git config --local user.name "Travis"
- export TRAVIS_AUTHOR=travis@randytarampi.ca
- export COMMIT_AUTHOR=`git --no-pager show -s --format='%ae' \`git rev-parse\``
- git config --local user.email $TRAVIS_AUTHOR
- if [ -z "$TRAVIS_TAG" ]; then if [[ "$TRAVIS_COMMIT_MESSAGE" != *"[Travis] Prepare version"* ]]; then
  npm version minor; git push https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG} --tags;
  HEAD:master; fi; fi;
deploy:
  provider: releases
  api_key:
    secure: NUochwMwiuB73it9PAm1n0W2Qu4/77/cgLAAnLDUCBEe7K/c/vZxkGufFMx81+jby9JR/2joCB9AnW5EdtPK/79QiIp4HpfA5dnvjCpoeaHGD8ekZPOg2V6P4m7kiO2z7lL547iYAwQ1A34r8cpynFrHdACJ4Nnw/Lx1i8vwDUSR/8FiOfJi7EO6d2OG6mAxe8SIlCE/tORdAogbOH7ItLumjFMk2bl/+1DKROr11TdbmwniGDxYGQnsmPHpQqZxbtFyy/RV4ihng2NHXrOWU/y1J4a4MhIfUXuTxXwRf2GD7hBnWCFRDLTrDzi/ZxTCoAJi32NEW8zl65ELcvsgXu/XIt8QZEpXtYvUvNA/zBi81N3b0akJW2l/Th8mHUmMw91u6UGMqt4P9mZSb21Iw6g5L6An/hawccJn9c8xoBQrHi2D9UWeX4frioGg5MII5MDz7YE+gZSil13cYUgo1+f1oI3MeHlcKc9CkmtmyGw0erR32o5Ose5i4xL6AftC/CswzyyEb25dPSBUt7gfNSuJSLMn7r2vOcKdffMYfmpwA9fDyy/4xJu9y73WqtBfMVfJMJDAaPr2RE7HCwd2Muh/69vuIqN0/FEMwoZ/vFVcfhG2oMut3aWqZbuNAHxhX/nlC/RFYTSib07i3jjudmvDCCGXSAMbQDhWfZEkBI8=
  file: me.words.tar.gz
  skip_cleanup: true
  on:
    tags: true
after_deploy:
- if [ "$TRAVIS_TAG" ]; then npm version preminor -m "[Travis] Prepare version %s";
  git push https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG} HEAD:master; fi;
notifications:
  slack:
    secure: bD1y+lFF6VseZ0bSi/fRqnFm2F6nil9pllhRh6ze24zmzHrftWHsvnuASZmn8MGKcqtnph/zyFKyVR+nDEXeQ04AZLU4tBoDbNWi2f85nzoUUD+8YzdQRctB9YIx818UGeZEVPBjIT1IVof+Z1AQEqM+jfl0LTNAPaADJgpLWDcNZDYNGUsibG4fapgix7P+vMTUgGFbN4J1WL243Q7pYK6x1hqOPNfDtaGSEFX7c1MUS6ULk335fkDo5M/o+vJweo0j2jboPN1n/vYpJuJRgmzP7jMISkchYjAKR2WktcM8CgC+mJye9NIaZQVn8IWEqqDYYIXM5IekEbTF2pz7bztaqgrhZdVmKqvl9edOfLL0qVt5RbguLuxSKsVw92AgajsiEhaOeNrA5gDyLq2o/xREtwpOC45M8wcJCAbHldqhjrJaRqpL2Q28mSGtmu7BDBWNwL2ylKE9NRTeY+e/ey5a70kUOorAKO5b8UhSJQJPEgBrNY1vTSb7F6eRmYkeqnqkTTMUEKIe+BtmnQ1kCPCbhDXk5BQoSumVxURAznj4SSzfamSMt1CUVpM/CPBsjui5plN1Ymwk/KvcstOkcCVU85vHS+Kare/j2n9J6wCexxiLsEUaImdldoLeUz6sVoTcy9OvWz+ohvM317gD5t/G8rHF1nWAr85s3Khx2GY=
